### PR TITLE
Rev.ai speech-to-text API converter

### PR DESCRIPTION
**Pull request by qmac**
Shameless self-promotion 😄

The Rev AI API should be more accurate and cheaper than the other APIs currently implemented in pliers (maybe only comparable with the Google "video" model for speech-to-text, which is more expensive). Already on our small obama_speech.wav test file, the transcript is essentially perfect. It should be particularly better for long-form audios such as podcasts, interviews, speeches, etc. One downside is the relatively slow turn-around time for short audios (in contrast to the relatively fast TAT for long audio).

Also in the PR:
-Miscellaneous linting updates
-Small bug fix for AudioToTextConverters where origin audio stim onset was being added twice

~Note: I added my trial credentials to travis, but these will expire after 300 free minutes~
Update: nevermind, realizing we cut "requires_payment" tests from travis

For more info: https://www.rev.ai/

### CODE REVIEW

**Comment by adelavega** [comment]
Awesome! What is "relatively slow" by the way?

**Comment by qmac** [comment]
<= 10s audio : ~30s
> 10s audio : 3 minutes average across all durations

**Comment by adelavega** [comment]
I think I can work with that ;)

**Comment by adelavega** [comment]
Hey, I gave it a shot on a movie stimulus. It was a fairly challenging stimulus, because it is scrambled at times, and it definitely seemed to do better than IBM had in the past. Although, I noticed it did not return onsets for the words, is that correct?

I'm curious to try against the "human" rev.ai service, as I think for us accuracy is more important than scalability/speed.

**Comment by qmac** [comment]
Hmm it should definitely return onsets, could be a bug in my implementation. Maybe send me the movie to test?

For the human-side, you can check out https://www.rev.com/api. It costs $1 a minute and turn around will be on the hours order of magnitude.

**Comment by adelavega** [comment]
This is the clip I tried it on: https://openneuro.org/crn/datasets/ds001545/snapshots/1.1.0/files/stimuli:cond1_run-01.mp4

**Comment by qmac** [comment]
Hmmmm I seem to get onsets+durations fine with that stimulus:
```
Thank 43.7 0.269999999999996
you 43.97 0.09000000000000341
Mr 44.12 0.240000000000002
Moshe 44.36 0.38000000000000256
You're 44.87 0.1700000000000017
most 45.07 0.4299999999999997
welcome 45.52 0.3200000000000003
as 45.84 0.12999999999999545
user 45.97 0.20000000000000284
stuff 46.19 0.28999999999999915
You're 48.08 0.12000000000000455
not 48.28 0.21999999999999886
going 48.5 0.1599999999999966
to 48.66 0.060000000000002274
be 48.72 0.2700000000000031
officially 48.99 0.4799999999999969
interviewed 49.47 0.480000000000004
Should 50.7 0.35999999999999943
I 51.06 0.05999999999999517
go 51.12 0.1600000000000037
like 51.31 0.22999999999999687
the 51.63 0.14999999999999858
Kendo 51.8 0.28000000000000114
```

**Comment by adelavega** [comment]
Hmm, odd but I'll take it!

**Comment by tyarkoni** [comment]
Looks great, thanks!!

**Pull request merged**
