### PR TITLE
Fix missing RGB

### LINKED ISSUE #295: GooglePropertyExtractor - VisionAPI not returning full RGB information
This look more like a bug with GoogleVisionAPI, but for some images (er rather just one), only "red" and "green" are returned in the response, but no blue, leading to a KeyError. I'm going to investigate if its because blue = 0, or because of a random fluke. It would be good to make the extractor robust to these possible responses.

    color = {'color': {'red': 68, 'green': 3}, 'score': 0.007824038, 'pixelFraction': 0.014705882}

https://github.com/tyarkoni/pliers/blob/a7ea0d2c69de92bf74388295de0a18311bf0a294/pliers/extractors/api/google.py#L112

### PR DESCRIPTION
**Pull request by adelavega**
Fixes #295

### CODE REVIEW

**Comment by qmac** [comment]
Potentially would not have occurred if we were wrapping `google-cloud-python` instead of directly requesting. But LGTM.

**Comment by adelavega** [comment]
Yes, looks like they fixed that in their python module, but not the API itself.

**Comment by adelavega** [comment]
Before this gets merged, I just found a related bug that should be addressed: the "feature_name" in `to_df` for this extractor is the R value, not the RGB combined.

**Comment by adelavega** [comment]
Fixed. @tyarkoni let me know if this looks reasonable.

**Pull request merged**
