### PR TITLE
version bump and Changelog update

### PR DESCRIPTION
**Pull request by tyarkoni**
0.3-related updates.

### CODE REVIEW

**Comment by qmac** [comment]
🎉

**Comment by tyarkoni** [comment]
Well... it's a muted celebration, because the Travis-CI tests are currently failing, and that's even without the paid tests (which are also broken, but only because of the usual changes to the returned results that require test updates). But I can't replicate the failures locally, so I figured it was probably safe to push a release. Will get to the root of the problem when time allows.

**Comment by qmac** [comment]
Weird, all the tests are passing....I see this as the error:
```
*** Error in `/home/travis/miniconda/envs/test-env/bin/python': corrupted size vs. prev_size: 0x000055a045855540 ***
```

**Comment by tyarkoni** [comment]
Yeah, sorry, the core dump on Travis is what I was referring to (though there are definitely failing paid tests--those are currently disabled on Travis because reasons).

**Pull request merged**
